site_name: Mailio
theme:
  name: material
  logo: img/icon-white-512x512.png
  favicon: favicon/favicon-32.png
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

nav:
  - Getting started: 'index.md'
  - Mailio Concepts: 'mailio_concepts.md'
  - Mailio Emergency Kit: 'smartkey.md'
  - How to: 'howtos.md'

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences

copyright: Copyright &copy; 2020 - Mailio

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/mailioio
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/realmailio
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mailio/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/realmailio
    - icon: fontawesome/solid/paper-plane
      link: mailto:Help Support <support@mail.io>